import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import {Bar} from 'react-chartjs-2';

const data = {
  labels: ['Infant', 'Child', 'Adult'],
  datasets: [{
    label: '# of Compressions',
    data: [115, 110, 100],
    backgroundColor: [
      'rgba(255, 99, 132, 0.2)',
      'rgba(54, 162, 235, 0.2)',
      'rgba(255, 206, 86, 0.2)'
    ],
    borderColor: [
      'rgba(255, 99, 132, 1)',
      'rgba(54, 162, 235, 1)',
      'rgba(255, 206, 86, 1)'
    ],
    borderWidth: 1
  }]
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className={styles.header}>
      <img src="/image.png" className={styles.image}/>
    </div>
      <div className={styles.main}>
        <div className={styles.infoHeader}>
            <h2>Recommended Compressions by Age Group</h2>
            <button>Download CSV</button>
        </div>
        
        <Bar
          width={100}
          height={60}
          data={data}
        />
      </div>
    </div>
  )
}
