import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import firebase from 'firebase/app';
import React from 'react';
import { useCollection } from 'react-firebase-hooks/firestore';
import {Bar} from 'react-chartjs-2';
import { firebaseConfig } from '../public/firebaseConfig.js';
import 'firebase/firestore';

const data = {
  labels: ['Infant', 'Child', 'Adult'],
  datasets: [{
    label: '# of Compressions',
    data: [115, 110, 100],
    backgroundColor: [
      'rgba(255, 99, 132, 0.2)',
      'rgba(54, 162, 235, 0.2)',
      'rgba(255, 206, 86, 0.2)'
    ],
    borderColor: [
      'rgba(255, 99, 132, 1)',
      'rgba(54, 162, 235, 1)',
      'rgba(255, 206, 86, 1)'
    ],
    borderWidth: 1
  }]
}

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

export default function Home() {
  const [value, loading, error] = useCollection(
    firebase.firestore().collection('cpr'),
    {
      snapshotListenOptions: { includeMetadataChanges: true },
    }
  );
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"></link>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>

    <div className={styles.header}>
      <img src="/image.png" className={styles.image}/>
    </div>
      <div className={styles.main}>
        <div className={styles.infoHeader}>
            <h2>Recommended Compressions by Age Group</h2>
            <button type="button" className="btn btn-primary"><i className="fas fa-file-download"></i> Download CSV</button>
        </div>
        
        <Bar
          width={100}
          height={60}
          data={data}
        />


      <div className={styles.infoHeader}>
            <h2>Survival Rate by Age Group</h2>
            <button type="button" className="btn btn-primary"><i className="fas fa-file-download"></i> Download CSV</button>
        </div>
        
        <p>
        {error && <strong>Error: {JSON.stringify(error)}</strong>}
        {loading && <span>Collection: Loading...</span>}
        {value && (
          <span>
            Collection:{' '}
            {value.docs.map((doc) => (
              <React.Fragment key={doc.id}>
                {JSON.stringify(doc.data())},{' '}
              </React.Fragment>
            ))}
          </span>
        )}
      </p>
        {/* <Bar
          width={100}
          height={60}
          data={data}
        /> */}
      </div>
    </div>
  )
}
